# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Method methods
email: plackmaker@method
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/method-methods" # the subpath of your site, e.g. /blog
url: "http://philiplackmaker.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
- project

# Build settings
markdown: kramdown
